import type { Metadata } from "next";
import { Playfair } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";



const playfair = Playfair({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Zbooks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
     <html lang="en">
        <body className={`${playfair.className} antialiased bg-[#FBFAF8]!`}>
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}