import type { Metadata } from "next";
import { Playfair } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { Suspense } from "react";

const playfair = Playfair({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Zbooks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${playfair.className} antialiased bg-[#FBFA8]`}>
          <Suspense fallback={<div>Loading...</div>}>
            {" "}
            <Navbar />
            {children}
          </Suspense>
        </body>
      </html>
    </ClerkProvider>
  );
}
